version: '3.7'

services:
  api:
    image: compiler-api-prod
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - 8002:8000
    environment:
      - NODE_ENV=production
    env_file:
      - ./api/.env
    depends_on:
      - db

  db:
    image: compiler-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    volumes:
      - canal-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  nginx:
    image: compiler-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - api
      - client

  client:
    image: compiler-client-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./client/.env
    depends_on:
      - api

volumes:
  canal-db-data: