name: rlxyz-compiler-publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        name: Install Packages
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: Format Solidity code.
        with:
          cmd: format
      - uses: borales/actions-yarn@v2.3.0
        name: Publish to NPM
        with:
          cmd: --cwd contracts publish
          auth-token: ${{ secrets.NPM_REGISTRY_TOKEN }}
